project:
  type: book
  output-dir: docs

book:
  title: "Laboratorio di Testing Psicologico"
  subtitle: "Anno Accademico 2024/2025"
  reader-mode: true

  author: "Corrado Caudek"
  date: "last-modified"
  search: true
  repo-url: https://github.com/ccaudek/labtestpsi/
  repo-actions: [edit]
  site-url: https://ccaudek.github.io/labtestpsi/intro.html
  page-footer:
    left: |
      **Laboratorio di Testing Psicologico** è una risorsa didattica creata per il Corso di Laurea Magistrale [PSICOLOGIA CLINICA E DELLA SALUTE E NEUROPSICOLOGIA](https://unifi.coursecatalogue.cineca.it/corsi/2024/3252?annoOrdinamento=2023) dell'[Università degli Studi di Firenze](https://www.unifi.it/). 
    right: |
      Realizzato con <a href="https://quarto.org/">Quarto</a>.
  sidebar:
    collapse-level: 1
    pinned: true

  chapters:
    - index.qmd

    - part: "Calendario"
      chapters:
        - programmazione2024.qmd

title-prefix: ""
toc: true
toc-depth: 3

bibliography: ./references.bib
biblio-style: apalike
csl: apa.csl
link-citations: true

lang: it

format:
  html:
    theme:
      light: [zephyr, css/custom.scss]
      dark: [zephyr, css/dark.scss, css/custom.scss]
    syntax-definitions:
      - theming/stan.xml
    # monofont: Fira Mono
    highlight-style: a11y
    code-copy: true
    code-overflow: wrap
    toc: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

editor: source

website:
  cookie-consent:
    type: express
    style: headline
  google-analytics:
    tracking-id: "G-TP2WLBPMS6"
    anonymize-ip: true

execute:
  freeze: auto
