{
  "hash": "4af548f0f11890f72b25c6a7097ed37b",
  "result": {
    "engine": "knitr",
    "markdown": "# Il teorema di Bayes {#sec-prob-bayes-theorem}\n\n::: callout-important\n## In questo capitolo imparerai a\n\n- capire in profondità il teorema di Bayes e la sua importanza;\n- utilizzare il teorema di Bayes per analizzare e interpretare i test diagnostici, tenendo in considerazione la prevalenza della malattia in questione;\n- affrontare e risolvere problemi di probabilità discreta che necessitano dell'applicazione del teorema di Bayes.\n:::\n\n::: callout-tip\n## Prerequisiti\n\n- Leggere *Everything is Predictable: How Bayesian Statistics Explain Our World* [@chivers2024everything]. Questo libro offre una descrizione chiara e accessibile dell'impatto che il teorema di Bayes ha avuto sulla vita moderna.\n- Leggere [Bayesian Models of Cognition](https://oecs.mit.edu/pub/lwxmte1p/release/2) di Thomas L. Griffiths, una voce della [Open Encyclopedia of Cognitive Science](https://oecs.mit.edu).\n:::\n\n::: callout-caution\n## Preparazione del Notebook\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhere::here(\"code\", \"_common.R\") |> \n  source()\n```\n:::\n\n\n\n:::\n\n> It is, without exaggeration, perhaps the most important single equation in history.\n>\n> Tom Chivers (2024)\n\n## Introduzione\n\nIl teorema di Bayes offre una soluzione ottimale ai problemi induttivi, che spaziano dall'identificazione della struttura tridimensionale del mondo basata su dati sensoriali limitati, all'inferenza dei pensieri altrui a partire dal loro comportamento. Questa regola si rivela particolarmente utile in situazioni in cui i dati osservati sono insufficienti per distinguere in modo definitivo tra diverse ipotesi.\n\nNonostante ciò, tutte le previsioni basate su questo metodo mantengono un certo grado di incertezza. Anche se l'universo fosse completamente deterministico, la nostra conoscenza di esso rimarrebbe imperfetta: non possiamo conoscere la posizione e lo stato di ogni singola particella che lo compone. Le informazioni a nostra disposizione sono inevitabilmente parziali e imprecise, ottenute attraverso i nostri sensi limitati.\n\nLa vita reale non è paragonabile a una partita di scacchi, un gioco con informazioni perfette che può essere \"risolto\" in linea di principio. Assomiglia piuttosto al poker, dove le decisioni vengono prese utilizzando le informazioni limitate a disposizione dei giocatori. Questo capitolo si concentra sull'equazione che ci permette di fare proprio questo: il teorema di Bayes. Esso descrive come modifichiamo le nostre convinzioni riguardo a un'ipotesi in una situazione in cui i dati disponibili non consentono una decisione certa.\n\nQuesto processo è noto come inferenza induttiva, che ci permette di trarre conclusioni generali da dati specifici e limitati. Il teorema di Bayes fornisce quindi un framework matematico per aggiornare le nostre credenze alla luce di nuove evidenze, permettendoci di prendere decisioni informate in un mondo caratterizzato dall'incertezza.\n\n## Una Rivoluzione nel Pensiero Probabilistico\n\nNel cuore del XVIII secolo, un ecclesiastico presbiteriano di nome Thomas Bayes gettò le basi per una delle più importanti rivoluzioni nel campo della statistica e del calcolo delle probabilità. Il suo contributo, noto oggi come teorema di Bayes, non solo ha trasformato il modo in cui comprendiamo e applichiamo la probabilità, ma continua a influenzare profondamente la scienza moderna e la tecnologia, inclusa l'intelligenza artificiale [@chivers2024everything].\n\nThomas Bayes nacque in una famiglia benestante e ricevette un'educazione di alto livello, studiando teologia a Edimburgo per prepararsi alla vita da ecclesiastico. Come nota il suo biografo Bellhouse, Bayes \"non sembrava un accademico moderno. Era più un dilettante, un virtuoso. Lo faceva per il proprio piacere piuttosto che avere un'agenda di ricerca.\"\n\nBayes pubblicò due opere principali durante la sua vita:\n\n1. Una di teologia, \"Divine benevolence: Or, an attempt to prove that the principal end of the divine providence and government is the happiness of his creatures\", nel 1731.\n2. Una difesa del calcolo newtoniano, \"An Introduction to the Doctrine of Fluxions\", in risposta a una critica del filosofo George Berkeley.\n\nTuttavia, fu il suo lavoro postumo, \"An Essay towards Solving a Problem in the Doctrine of Chances\", pubblicato nel 1763 nella rivista *Philosophical Transactions*, a cambiare per sempre il corso della teoria della probabilità.\n\nBellhouse nota che l'interesse di Bayes per la matematica era tipico del suo tempo: \"Nel XVIII secolo, i ricchi si dedicavano alla scienza. È un po' come i ricchi di oggi che si dedicano agli sport.\" Ma forse Bellhouse si riferiva solo al suo tempo: oggi i ricchi sembrano interessarsi solo ai social media.\n\nIl contributo di Bayes non fu tanto matematico quanto filosofico. David Spiegelhalter, ex presidente della Royal Statistical Society, spiega che per Bayes \"la probabilità è un'espressione della nostra mancanza di conoscenza sul mondo.\" Questa visione introduce l'idea rivoluzionaria che la probabilità sia soggettiva, un'espressione della nostra conoscenza limitata e delle nostre supposizioni sulla verità, piuttosto che una proprietà oggettiva della realtà.\n\nPer illustrare questo concetto, Bayes utilizzò l'esempio di un tavolo nascosto alla vista su cui vengono lanciate delle palle. Una palla bianca viene lanciata in modo tale che la sua posizione finale sia completamente casuale. Quando la palla bianca si ferma, viene rimossa e si traccia una linea sul tavolo nel punto in cui si trovava. La posizione della linea non è nota. Successivamente, un certo numero di palle rosse viene lanciato sul tavolo. Viene comunicato solo quante palle si trovano a sinistra della linea e quante a destra. Il compito è stimare la posizione della linea. La soluzione proposta da Bayes utilizza non solo i dati osservati (il numero di palle rosse a sinistra e a destra della linea), ma anche le convinzioni iniziali (il \"prior\").\n\nRichard Price (1723-1791), un altro ecclesiastico nonconformista, ebbe un ruolo cruciale nella diffusione del lavoro di Thomas Bayes. Molto più noto del suo amico, Price era ben inserito nei circoli intellettuali dell'epoca. Era in contatto con diversi Padri Fondatori della Rivoluzione Americana, tra cui Thomas Jefferson e Benjamin Franklin, così come John Adams, il secondo presidente degli Stati Uniti. Supportava attivamente la rivoluzione americana, pubblicando un influente opuscolo *Observations on the Nature of Civil Liberty, the Principles of Government, and the Justice and Policy of the War with America* nel 1776. Era amico di filosofi come David Hume e Adam Smith.\n\nPrice è importante in questa storia come colui che portò all'attenzione pubblica il lavoro di Bayes: mostrò il saggio al fisico John Canton nel 1761, dopo la morte di Bayes, e lo fece pubblicare nelle *Philosophical Transactions* della Royal Society due anni dopo. Parte del motivo per cui ci volle tanto tempo per pubblicarlo era che Price non si limitò a correggere refusi e virgole fuori posto. Price aveva una visione propria del lavoro: mentre Bayes scrisse la prima metà del saggio, la seconda metà, contenente tutte le possibili applicazioni pratiche del teorema, fu tutta opera di Price. Bayes non aveva interesse per le statistiche applicate: il suo lavoro, in questo e in tutti gli altri articoli, era \"tutta teoria senza alcun accenno di applicazione.\" Ma Price fu -- come dice lo storico della statistica Stephen Stigler -- \"il primo bayesiano.\"\n\nSebbene il lavoro di Bayes sia rimasto nell'ombra per decenni, con Pierre-Simon Laplace che giunse indipendentemente a conclusioni simili nel 1774 e le espanse nella sua \"Théorie analytique des probabilités\" del 1812, l'importanza del teorema di Bayes è oggi indiscutibile. Esso fornisce un meccanismo matematico per aggiornare le probabilità di un'ipotesi in base a nuove evidenze, riflettendo un approccio dinamico e iterativo alla conoscenza.\n\nNel panorama contemporaneo, il teorema di Bayes trova applicazioni in ogni campo della scienza e della tecnologia. È particolarmente rilevante nel campo dell'intelligenza artificiale, dove modelli linguistici avanzati come ChatGPT e Claude utilizzano principi bayesiani per fare previsioni e prendere decisioni.\n\nIn conclusione, il teorema di Bayes, nato dalle riflessioni di un ministro presbiteriano del XVIII secolo, ha trasformato il nostro modo di comprendere la probabilità e di aggiornare le nostre conoscenze. La sua rilevanza universale nella comprensione e previsione dei fenomeni è tale che, come afferma Brian Clegg nel suo libro \"Everything is predictable: how bayesian statistics explain our world\", la statistica bayesiana è diventata uno strumento fondamentale per spiegare il nostro mondo [@chivers2024everything].\n\n## La Regola di Bayes\n\nL'inferenza bayesiana si basa su una formula fondamentale nota come **regola di Bayes**. Sebbene sia un semplice risultato della teoria delle probabilità, la sua applicazione ha implicazioni profonde in molti campi, inclusi la scienza cognitiva e l'apprendimento automatico. Supponiamo di avere due variabili casuali, $A$ e $B$. Un principio della probabilità, chiamato **regola della catena**, ci consente di esprimere la probabilità congiunta di queste due variabili $P(A, B)$ come il prodotto della probabilità condizionale di $A$ dato $B$ e della probabilità marginale di $B$. In termini formali:\n\n$$\nP(A, B) = P(A \\mid B) P(B).\n$$ {#eq-chain-1}\n\nNon vi è nulla di speciale nel trattare $A$ prima di $B$; possiamo infatti scrivere anche:\n\n$$\nP(A, B) = P(B \\mid A) P(A).\n$$ {#eq-chain-2}\n\nDalle due equazioni precedenti possiamo derivare la regola di Bayes riorganizzando i termini:\n\n$$\nP(B \\mid A) = \\frac{P(A \\mid B) P(B)}{P(A)}.\n$$ {#eq-bayes-rule-1}\n\nQuesta espressione, nota come **regola di Bayes**, ci permette di calcolare la probabilità condizionale di $B$ dato $A$, usando la probabilità condizionale opposta $P(A \\mid B)$, la probabilità a priori $P(B)$ e la probabilità marginale $P(A)$.\n\n---\n\n## Applicazioni della Regola di Bayes\n\nLa forza della regola di Bayes si manifesta pienamente quando viene applicata al contesto dell'inferenza. Supponiamo di avere un agente che cerca di inferire quale processo ha generato alcuni dati $D$. Indichiamo con $H$ un'ipotesi su tale processo. L'agente usa le probabilità per rappresentare il grado di credenza in $H$ e nelle ipotesi alternative $H'$. La probabilità a priori $P(H)$ rappresenta la credenza che l'agente attribuisce a $H$ prima di osservare i dati.\n\nQuando l'agente osserva i nuovi dati $D$, aggiorna la credenza ottenendo la **probabilità a posteriori** $P(H \\mid D)$. La regola di Bayes permette di calcolare questa probabilità come segue:\n\n$$\nP(H \\mid D) = \\frac{P(D \\mid H) P(H)}{P(D)}.\n$$ {#eq-bayes-rule-2}\n\nIn questa equazione:\n\n- $P(D \\mid H)$: la **verosimiglianza**, ovvero la probabilità di osservare i dati $D$ assumendo che l'ipotesi $H$ sia vera. Questa componente valuta quanto l'ipotesi predice i dati osservati.\n- $P(H)$: la **probabilità a priori** di $H$.\n- $P(D)$: la **probabilità marginale** dei dati, calcolata sommando (o integrando) le probabilità congiunte per tutte le ipotesi $H'$.\n\n---\n\n### La Marginalizzazione\n\nLa probabilità marginale di $D$, necessaria per normalizzare la distribuzione a posteriori, si ottiene considerando tutte le ipotesi possibili $H'$. Per ipotesi discrete, la somma è:\n\n$$\nP(D) = \\sum_{H' \\in H} P(D \\mid H') P(H').\n$$\n\nSostituendo questa espressione nella regola di Bayes otteniamo:\n\n$$\nP(H \\mid D) = \\frac{P(D \\mid H) P(H)}{\\sum_{H' \\in H} P(D \\mid H') P(H')}.\n$$ {#eq-marginal-prob}\n\nNel caso continuo, la somma è sostituita da un integrale:\n\n$$\nP(H \\mid D) = \\frac{P(D \\mid H) P(H)}{\\int P(D \\mid H') P(H') \\, dH'}.\n$$ {#eq-bayes-rule-cont}\n\n---\n\n### Componenti Chiave della Formula di Bayes\n\nLa regola di Bayes si basa su tre componenti principali:\n\n1. **Probabilità a Priori $P(H)$**: La credenza iniziale sull'ipotesi $H$, basata su informazioni preesistenti.\n2. **Verosimiglianza $P(D \\mid H)$**: La probabilità dei dati osservati $D$, dato che $H$ sia vera. Misura quanto $H$ spiega $D$.\n3. **Probabilità a Posteriori $P(H \\mid D)$**: La credenza aggiornata in $H$ dopo aver osservato $D$.\n\nGrazie alla regola di Bayes, possiamo aggiornare costantemente le nostre credenze man mano che nuove informazioni diventano disponibili. Questo processo dinamico di aggiornamento ci permette di affinare le nostre convinzioni e le nostre previsioni, rendendo il modello bayesiano particolarmente utile nelle situazioni in cui le informazioni sono incomplete o incerte. Questo approccio non solo ci consente di prendere decisioni più informate, ma ci permette anche di sviluppare modelli più accurati della realtà basati sulle evidenze.\n\n### Applicazioni dei modelli bayesiani\n\nCome discusso da @griffiths2024bayesian, negli ultimi anni, i modelli bayesiani hanno acquisito un'importanza crescente in vari campi delle scienze cognitive. Questi modelli sono stati applicati allo studio dell'apprendimento animale (Courville, Daw, & Touretzky, 2006), dell'apprendimento induttivo umano e della generalizzazione (Tenenbaum, Griffiths, & Kemp, 2006), della percezione visiva (Yuille & Kersten, 2006), del controllo motorio (Kording & Wolpert, 2006), della memoria semantica (Steyvers, Griffiths, & Dennis, 2006), dell'acquisizione e del processamento del linguaggio (Chater & Manning, 2006; Xu & Tenenbaum, in press), del ragionamento simbolico (Oaksford & Chater, 2001), dell'apprendimento causale (Steyvers, Tenenbaum, Wagenmakers, & Blum, 2003; Griffiths & Tenenbaum, 2005, 2007a), e della cognizione sociale (Baker, Tenenbaum, & Saxe, 2007), tra molti altri argomenti.\n\nDietro questi diversi programmi di ricerca emerge una domanda centrale: **come fa la mente umana ad andare oltre i dati dell'esperienza?** In altre parole, come riesce la mente a costruire modelli complessi e astratti del mondo, partendo solo da dati sparsi e rumorosi, osservati attraverso i nostri sensi? La risposta proposta dall'approccio bayesiano è che la mente umana utilizza un processo di inferenza probabilistica per aggiornare le proprie credenze sulla base delle nuove evidenze, creando così modelli del mondo sempre più accurati e raffinati.\n\n## Test medici\n\nIl modo più comune per spiegare il teorema di Bayes è attraverso i test medici.\n\n::: {#exm-}\nPrendiamo come esempio il caso della mammografia e la diagnosi del cancro al seno che abbiamo già discusso in precedenza. Supponiamo di avere un test di mammografia con una sensibilità del 90% e una specificità del 90%. Questo significa che:\n\n- In presenza di cancro al seno, la probabilità che il test lo rilevi correttamente è del 90%.\n- In assenza di cancro al seno, la probabilità che il test confermi correttamente l'assenza della malattia è del 90%.\n\nIn altri termini, il test ha un tasso di falsi negativi del 10% e un tasso di falsi positivi anch'esso del 10%.\n\nDefiniamo due ipotesi:\n\n1. $M^+$: presenza della malattia\n2. $M^-$: assenza della malattia\n\nL'evidenza è rappresentata dal risultato positivo di un test di mammografia, che indichiamo con $T^+$.\n\nApplicando il teorema di Bayes, possiamo calcolare la probabilità di avere il cancro al seno dato un risultato positivo al test, come segue:\n\n$$\nP(M^+ \\mid T^+) = \\frac{P(T^+ \\mid M^+) \\cdot P(M^+)}{P(T^+ \\mid M^+) \\cdot P(M^+) + P(T^+ \\mid M^-) \\cdot P(M^-)},\n$$\n\ndove:\n\n- $P(M^+ \\mid T^+)$ è la probabilità di avere il cancro ($M^+$) dato un risultato positivo al test ($T^+$).\n- $P(T^+ \\mid M^+)$ rappresenta la sensibilità del test, ovvero la probabilità che il test risulti positivo in presenza effettiva del cancro. In questo caso, è pari a 0.90.\n- $P(M^+)$ è la probabilità a priori che una persona abbia il cancro, ovvero la prevalenza della malattia nella popolazione.\n- $P(T^+ \\mid M^-)$ indica la probabilità di un falso positivo, cioè la probabilità che il test risulti positivo in assenza di cancro. Con una specificità del 90%, questa probabilità si calcola come:\n\n  $$\n  P(T^+ \\mid M^-) = 1 - \\text{Specificità} = 1 - 0.90 = 0.10\n  $$\n\n  Questo significa che c'è una probabilità del 10% che il test diagnostichi erroneamente la presenza del cancro in una persona sana.\n\n- $P(M^-)$ è la probabilità a priori che una persona non sia affetta da cancro prima di effettuare il test.\n\nQuesta formulazione del teorema di Bayes ci permette di calcolare la probabilità effettiva di avere il cancro al seno, dato un risultato positivo al test di mammografia, tenendo conto sia della sensibilità e specificità del test, sia della prevalenza della malattia nella popolazione.\n\nInserendo nella formula i del problema, otteniamo:\n\n$$\n\\begin{align}\nP(M^+ \\mid T^+) &= \\frac{0.9 \\cdot 0.01}{0.9 \\cdot 0.01 + 0.1 \\cdot 0.99} \\notag\\\\\n&= \\frac{9}{108} \\notag\\\\\n&\\approx 0.083.\\notag\n\\end{align}\n$$\n\nI calcoli effettuati evidenziano come, in presenza di una mammografia positiva ottenuta con un test avente sensibilità e specificità pari al 90%, la probabilità di effettiva positività al tumore al seno si attesta intorno all'8.3%. Tale risultato conferma quanto precedentemente ottenuto nel @sec-cond-prob, attraverso un metodo di calcolo alternativo.\n:::\n\n### Il Valore Predittivo di un Test di Laboratorio\n\nPer semplicità, possiamo riscrivere il teorema di Bayes in due modi distinti per calcolare ciò che viene chiamato valore predittivo del test positivo e valore predittivo del test negativo.\n\nLa comprensione di tre elementi è fondamentale per questo calcolo: la prevalenza della malattia, la sensibilità e la specificità del test.\n\n- **Prevalenza:** Si riferisce alla percentuale di individui in una popolazione affetti da una certa malattia in un determinato momento. Viene espressa come percentuale o frazione della popolazione. Per esempio, una prevalenza dello 0,5% indica che su mille persone, cinque sono affette dalla malattia.\n\n- **Sensibilità:** Indica la capacità del test di identificare correttamente la malattia negli individui malati. Viene calcolata come la frazione di veri positivi (individui malati correttamente identificati) sul totale degli individui malati. La formula della sensibilità ($Sens$) è la seguente:\n\n    $$ \\text{Sensibilità} = \\frac{TP}{TP + FN}, $$\n\n    dove $TP$ rappresenta i veri positivi e $FN$ i falsi negativi. Pertanto, la sensibilità misura la probabilità che il test risulti positivo se la malattia è effettivamente presente.\n\n- **Specificità:** Misura la capacità del test di riconoscere gli individui sani, producendo un risultato negativo per chi non è affetto dalla malattia. Si calcola come la frazione di veri negativi (individui sani correttamente identificati) sul totale degli individui sani. La specificità ($Spec$) si definisce come:\n\n    $$ \\text{Specificità} = \\frac{TN}{TN + FP}, $$\n\n    dove $TN$ sono i veri negativi e $FP$ i falsi positivi. Così, la specificità rappresenta la probabilità che il test risulti negativo in assenza della malattia.\n\nQuesta tabella riassume la terminologia:\n\n|       | $T^+$                                              | $T^-$                                              | Totale              |\n| :---: | :------------------------------------------------: | :------------------------------------------------: | :------------------:|\n| $M^+$ | $P(T^+ \\cap M^+)$ <br> (Sensibilità)               | $P(T^- \\cap M^+)$ <br> (1 - Sensibilità)           | $P(M^+)$            |\n| $M^-$ | $P(T^+ \\cap M^-)$ <br> (1 - Specificità)           | $P(T^- \\cap M^-)$ <br> (Specificità)               | $P(M^-)$            |\n| Totale| $P(T^+)$                                           | $P(T^-)$                                           | 1                   |\n\ndove $T^+$ e $T^-$ indicano rispettivamente un risultato positivo o negativo del test, mentre $M^+$ e $M^-$ la presenza o assenza effettiva della malattia. In questa tabella, i totali marginali rappresentano:\n\n- **Totale per $M^+$ e $M^-$** (ultima colonna): La probabilità totale di avere la malattia ($P(M^+)$) e la probabilità totale di non avere la malattia ($P(M^-)$), rispettivamente. Questi valori sono calcolati sommando le probabilità all'interno di ciascuna riga.\n- **Totale per $T^+$ e $T^-$** (ultima riga): La probabilità totale di un risultato positivo al test ($P(T^+)$) e la probabilità totale di un risultato negativo al test ($P(T^-)$), rispettivamente. Questi valori sono calcolati sommando le probabilità all'interno di ciascuna colonna.\n- **Totale generale** (angolo in basso a destra): La somma di tutte le probabilità, che per definizione è 1, rappresentando l'intera popolazione o il set di casi considerati.\n\nMediante il teorema di Bayes, possiamo usare queste informazioni per stimare la probabilità post-test di avere o non avere la malattia basandoci sul risultato del test.\n\nIl **valore predittivo positivo** (VPP) del test, cioè la probabilità post-test che un individuo sia malato dato un risultato positivo del test, è calcolato come:\n\n$$\nP(M^+ \\mid T^+) = \\frac{P(T^+ \\mid M^+) \\cdot P(M^+)}{P(T^+ \\mid M^+) \\cdot P(M^+) + P(T^+ \\mid M^-) \\cdot P(M^-)}.\n$$\n\novvero,\n\n$$ VPP = \\frac{(\\text{Sensibilità} \\times \\text{Prevalenza})}{(\\text{Sensibilità} \\times \\text{Prevalenza}) + (1 - \\text{Specificità}) \\times (1 - \\text{Prevalenza})} $$\n\nAnalogamente, il **valore predittivo negativo** (VPN), che è la probabilità che un individuo non sia malato dato un risultato negativo del test, si calcola come:\n\n$$\nP(M^- \\mid T^-) = \\frac{P(T^- \\mid M^-) \\cdot (1 - P(M^+))}{P(T^- \\mid M^-) \\cdot (1 - P(M^+)) + P(T^- \\mid M^+) \\cdot P(M^+)}.\n$$\n\novvero,\n\n$$ NPV = \\frac{\\text{Specificità} \\cdot (1 - \\text{Prevalenza})}{\\text{Specificità} \\cdot (1 - \\text{Prevalenza}) + (1 - \\text{Sensibilità}) \\cdot \\text{Prevalenza}}. $$\n\n::: {#exm-}\n\nImplementiamo le formule del valore predittivo positivo e del valore predittivo negativo del test in R e usiamo gli stessi dati dell'esercizio precedente.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npositive_predictive_value_of_diagnostic_test <- function(sens, spec, prev) {\n  (sens * prev) / (sens * prev + (1 - spec) * (1 - prev))\n}\n\nnegative_predictive_value_of_diagnostic_test <- function(sens, spec, prev) {\n  (spec * (1 - prev)) / (spec * (1 - prev) + (1 - sens) * prev)\n}\n```\n:::\n\n\n\n\nInseriamo i dati del problema.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsens = 0.9  # sensibilità\nspec = 0.9  # specificità\nprev = 0.01  # prevalenza\n```\n:::\n\n\n\n\nIl valore predittivo del test positivo è:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres_pos <- positive_predictive_value_of_diagnostic_test(sens, spec, prev)\ncat(sprintf(\"P(M+ | T+) = %.3f\\n\", res_pos))\n#> P(M+ | T+) = 0.083\n```\n:::\n\n\n\n\nIl valore predittivo del test negativo è:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres_neg <- negative_predictive_value_of_diagnostic_test(sens, spec, prev)\ncat(sprintf(\"P(M- | T-) = %.3f\\n\", res_neg))\n#> P(M- | T-) = 0.999\n```\n:::\n\n\n\n:::\n\n::: {#exm-3a}\n\nLa simulazione seguente ha lo scopo di aiutare a visualizzare il teorema di Bayes, utilizzando come esempio gli stessi dati della mammografia che abbiamo analizzato in precedenza.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Parametri\nsensitivity <- 0.90  # Sensibilità del test (P(T+ | M+))\nspecificity <- 0.90  # Specificità del test (P(T- | M-))\nprev_cancer <- 0.01  # Prevalenza (P(M+))\n\n# Simulazione per una popolazione di 100.000 persone\nN_mammography <- 100000\n\n# Generazione del campione casuale\nset.seed(123)\noutcome_mammography <- sample(\n  c(\"Cancer\", \"Healthy\"), \n  N_mammography, \n  replace = TRUE, \n  prob = c(prev_cancer, 1 - prev_cancer)\n)\n\n# Conteggio delle persone con e senza cancro\nN_C <- sum(outcome_mammography == \"Cancer\")\nN_H <- sum(outcome_mammography == \"Healthy\")\n\n# Simulazione dei risultati del test\ntest_mammography <- character(N_mammography)\ntest_mammography[outcome_mammography == \"Cancer\"] <- sample(\n  c(\"+\", \"-\"), \n  N_C, \n  replace = TRUE, \n  prob = c(sensitivity, 1 - sensitivity)\n)\ntest_mammography[outcome_mammography == \"Healthy\"] <- sample(\n  c(\"-\", \"+\"), \n  N_H, \n  replace = TRUE, \n  prob = c(specificity, 1 - specificity)\n)\n\n# Creazione di un data frame per memorizzare i risultati\ndf_mammography <- tibble(\n  outcome = outcome_mammography,\n  test = test_mammography\n)\n\n# Creazione di una tabella di contingenza\ncontingency_table_mammography <- df_mammography %>%\n  count(outcome, test) %>%\n  pivot_wider(names_from = test, values_from = n, values_fill = 0)\n\ncontingency_table_mammography\n#> # A tibble: 2 × 3\n#>   outcome   `+`   `-`\n#>   <chr>   <int> <int>\n#> 1 Cancer    911   114\n#> 2 Healthy  9897 89078\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calcolo delle probabilità basate sulla tabella di contingenza\n\n# Veri positivi (cancro e risultato positivo al test)\ntrue_positives <- contingency_table_mammography %>%\n  filter(outcome == \"Cancer\") %>%\n  pull(`+`)\n\n# Falsi positivi (sani e risultato positivo al test)\nfalse_positives <- contingency_table_mammography %>%\n  filter(outcome == \"Healthy\") %>%\n  pull(`+`)\n\n# Frequenza totale dei risultati positivi\ntotal_positives <- true_positives + false_positives\n\n# Applicazione del teorema di Bayes sui dati simulati\nP_M_given_T <- true_positives / total_positives\nP_M_given_T\n#> [1] 0.0843\n```\n:::\n\n\n\n\nUtilizzando i dati della simulazione, la probabilità che una persona abbia il cancro al seno dato un risultato positivo al test è molto vicina al valore teorico calcolato in precedenza (circa 8.3%). Se eseguissimo la simulazione nuovamente, il valore ottenuto potrebbe variare leggermente a causa della casualità intrinseca nel campionamento. Tuttavia, ripetendo la simulazione molte volte, i risultati tenderanno a convergere verso il valore teorico, grazie alla legge dei grandi numeri. Questo conferma che il modello teorico è coerente con i risultati simulati.\n\n:::\n\n:::{#exm-hiv}\n\nPoniamoci il problema di capire quanto sia affidabile un test per l'HIV. Per fare questo, utilizzeremo le seguenti informazioni [@petersen2024principles]:\n\n- **Tasso di base dell'HIV (P(HIV))**: 0.3% (0.003). Questa è la probabilità che una persona nella popolazione generale abbia l'HIV.\n- **Sensibilità del test (P(Test+ \\mid HIV))**: 95% (0.95). Questa è la probabilità che il test risulti positivo se la persona ha effettivamente l'HIV.\n- **Specificità del test (P(Test- \\mid ¬HIV))**: 99.28% (0.9928). Questa è la probabilità che il test risulti negativo se la persona non ha l'HIV.\n\n**Calcolo della probabilità di HIV dato un test positivo.**\n\nPer calcolare la probabilità di avere l'HIV dato un test positivo (P(HIV \\mid Test+)), utilizziamo il teorema di Bayes:\n\n$$\nP(HIV \\mid Test+) = \\frac{P(Test+ \\mid HIV) \\times P(HIV)}{P(Test+)}.\n$$\n\nAbbiamo bisogno di calcolare il denominatore, ovvero la probabilità complessiva di ottenere un test positivo (P(Test+)). Questo valore include sia i veri positivi che i falsi positivi:\n\n$$\nP(Test+) = P(Test+ \\mid HIV) \\times P(HIV) + P(Test+ \\mid \\neg HIV) \\times P(\\neg HIV),\n$$\n\ndove:\n\n- $P(Test+ \\mid \\neg HIV) = 1 - P(Test- \\mid \\neg HIV) = 1 - 0.9928 = 0.0072$ (tasso di falsi positivi),\n- $P(\\neg HIV) = 1 - P(HIV) = 1 - 0.003 = 0.997$.\n\nCalcoliamo $P(Test+)$:\n\n$$\nP(Test+) = (0.95 \\times 0.003) + (0.0072 \\times 0.997) \\approx 0.010027.\n$$\n\nOra possiamo calcolare $P(HIV \\mid Test+)$:\n\n$$\nP(HIV \\mid Test+) = \\frac{0.95 \\times 0.003}{0.010027} \\approx 0.2844 \\text{ o 28.44\\%}.\n$$\n\nQuindi, se il test risulta positivo, la probabilità di avere l'HIV è circa il 28.44%.\n\n**Calcolo della probabilità di un secondo test positivo.**\n\nDopo un primo test positivo, la probabilità di avere l'HIV è aumentata al 28.44%. Ora calcoleremo la probabilità che un secondo test risulti positivo e la conseguente probabilità di avere l'HIV dopo due test positivi consecutivi.\n\nPer calcolare $P(\\text{Secondo Test+})$, consideriamo due scenari:\n\n1. La persona ha effettivamente l'HIV:\n   - Probabilità: $P(HIV \\mid Test+) = 0.2844$.\n   - Probabilità di un test positivo: $P(\\text{Test+} \\mid HIV) = 0.95$ (sensibilità del test).\n\n2. La persona non ha l'HIV:\n   - Probabilità: $P(\\neg HIV \\mid Test+) = 1 - P(HIV \\mid Test+) = 0.7156$.\n   - Probabilità di un test positivo: $P(\\text{Test+} \\mid \\neg HIV) = 0.0072$ (tasso di falsi positivi).\n\nUtilizziamo la formula della probabilità totale:\n\n$$\n\\begin{aligned}\nP(\\text{Secondo Test+}) &= P(\\text{Test+} \\mid HIV) \\times P(HIV \\mid Test+) + \\\\\n&\\quad P(\\text{Test+} \\mid \\neg HIV) \\times P(\\neg HIV \\mid Test+).\n\\end{aligned}\n$$\n\nSostituendo i valori:\n\n$$\nP(\\text{Secondo Test+}) = (0.95 \\times 0.2844) + (0.0072 \\times 0.7156) \\approx 0.2753.\n$$\n\nApplichiamo nuovamente il teorema di Bayes per calcolare la probabilità di avere l'HIV dopo un secondo test positivo:\n\n$$\nP(HIV \\mid \\text{Secondo Test+}) = \\frac{P(\\text{Secondo Test+} \\mid HIV) \\times P(HIV \\mid Test+)}{P(\\text{Secondo Test+})}.\n$$\n\nSostituendo i valori:\n\n$$\nP(HIV \\mid \\text{Secondo Test+}) = \\frac{0.95 \\times 0.2844}{0.2753} \\approx 0.981.\n$$\n\nDopo un secondo test positivo, la probabilità di avere l'HIV aumenta significativamente, passando dal 28.44% al 98.1%. Questo aumento drastico dimostra l'importanza di:\n\n1. Considerare il tasso di base (prevalenza) nella popolazione.\n2. Aggiornare progressivamente le probabilità con nuove evidenze.\n3. Interpretare i risultati di test diagnostici multipli in modo bayesiano.\n\nL'analisi evidenzia come l'accumulo di evidenze attraverso test ripetuti, in linea con i principi del teorema di Bayes, possa portare a una stima molto più accurata della probabilità di avere una condizione medica, riducendo significativamente l'incertezza iniziale.\n\n:::\n\n::: {#exm-}\n\nConsideriamo ora un altro esempio relativo ai test medici e analizziamo i risultati del test antigenico rapido per il virus SARS-CoV-2 alla luce del teorema di Bayes. Questo test può essere eseguito mediante tampone nasale, tampone naso-orofaringeo o campione di saliva. L'Istituto Superiore di Sanità, nel documento pubblicato il 5 novembre 2020, sottolinea che, fino a quel momento, i dati disponibili sui vari test erano quelli forniti dai produttori: la sensibilità varia tra il 70% e l'86%, mentre la specificità si attesta tra il 95% e il 97%.\n\nPrendiamo un esempio specifico: nella settimana tra il 17 e il 23 marzo 2023, in Italia, il numero di individui positivi al virus è stato stimato essere di 138.599 (fonte: Il Sole 24 Ore). Questo dato corrisponde a una prevalenza di circa lo 0,2% su una popolazione totale di circa 59 milioni di persone.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n prev = 138599 / 59000000\n prev\n#> [1] 0.00235\n```\n:::\n\n\n\n\nL'obiettivo è determinare la probabilità di essere effettivamente affetti da Covid-19, dato un risultato positivo al test antigenico rapido, ossia $P(M^+ \\mid T^+)$. Per raggiungere questo scopo, useremo la formula relativa al valore predittivo positivo del test.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calcolo della sensibilità e specificità medie\nsens <- (0.7 + 0.86) / 2  # sensibilità\nspec <- (0.95 + 0.97) / 2 # specificità\n\n# Calcolo del valore predittivo positivo\nres_pos <- positive_predictive_value_of_diagnostic_test(sens, spec, prev)\ncat(sprintf(\"P(M+ | T+) = %.3f\\n\", res_pos))\n#> P(M+ | T+) = 0.044\n```\n:::\n\n\n\n\nPertanto, se il risultato del tampone è positivo, la probabilità di essere effettivamente affetti da Covid-19 è solo del 4.4%.\n\nSe la prevalenza fosse 100 volte superiore (cioè, pari al 23.5%), la probabilità di avere il Covid-19, dato un risultato positivo del tampone, aumenterebbe notevolmente e sarebbe pari a circa l'86%.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calcolo della prevalenza aumentata di 100 volte\nprev <- 138599 / 59000000 * 100\n\n# Calcolo del valore predittivo positivo\nres_pos <- positive_predictive_value_of_diagnostic_test(sens, spec, prev)\ncat(sprintf(\"P(M+ | T+) = %.3f\\n\", res_pos))\n#> P(M+ | T+) = 0.857\n```\n:::\n\n\n\n\nSe il risultato del test fosse negativo, considerando la prevalenza stimata del Covid-19 nella settimana dal 17 al 23 marzo 2023, la probabilità di non essere infetto sarebbe del 99.9%.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calcolo della sensibilità, specificità e prevalenza\nsens <- (0.7 + 0.86) / 2  # sensibilità\nspec <- (0.95 + 0.97) / 2  # specificità\nprev <- 138599 / 59000000  # prevalenza\n\n# Calcolo del valore predittivo negativo\nres_neg <- negative_predictive_value_of_diagnostic_test(sens, spec, prev)\ncat(sprintf(\"P(M- | T-) = %.3f\\n\", res_neg))\n#> P(M- | T-) = 0.999\n```\n:::\n\n\n\n\nTuttavia, un'esito del genere non dovrebbe sorprenderci, considerando che la prevalenza della malattia è molto bassa; in altre parole, il risultato negativo conferma una situazione già presunta prima di sottoporsi al test. Il vero ostacolo, specialmente nel caso di malattie rare come il Covid-19 in quel periodo specifico, non risiede tanto nell'asserire l'assenza della malattia quanto piuttosto nel confermarne la presenza.\n\n:::\n\n::: {#exm-}\n\nConsideriamo le persone in attesa di un figlio. Il teorema di Bayes gioca un ruolo cruciale nell'interpretazione dei test prenatali non invasivi (NIPT), un esame del sangue materno usato per rilevare anomalie cromosomiche fetali. Sebbene il NIPT sia spesso pubblicizzato con un'accuratezza del 99%, la sua affidabilità varia significativamente a seconda della condizione testata e della popolazione esaminata.\n\nParametri chiave del NIPT:\n\n1. Sensibilità:\n\n   - Sindrome di Down: 99%\n   - Sindrome di Edwards: 97%\n   - Sindrome di Patau: 91%\n\n2. Specificità: circa 99.9% per tutte le condizioni citate\n\n3. Prevalenza nelle nascite:\n\n   - Sindrome di Down: 1 su 700 (0.14%)\n   - Sindrome di Edwards: 1 su 5,000 (0.02%)\n   - Sindrome di Patau: 1 su 10,000 (0.01%)\n\nNonostante l'alta sensibilità e specificità, il VPP può essere sorprendentemente basso, soprattutto nella popolazione generale. Questo implica che molti risultati positivi potrebbero essere falsi positivi, in particolare per le condizioni più rare.\n\nPer calcolare il VPP, utilizziamo il teorema di Bayes:\n\n$$ VPP = \\frac{(\\text{Sensibilità} \\times \\text{Prevalenza})}{(\\text{Sensibilità} \\times \\text{Prevalenza}) + (1 - \\text{Specificità}) \\times (1 - \\text{Prevalenza})} $$\n\nApplicando questa formula alla popolazione generale:\n\n- Sindrome di Down:\n  $$ VPP = \\frac{(0.99 \\times 0.0014)}{(0.99 \\times 0.0014) + (1 - 0.999) \\times (1 - 0.0014)} \\approx 58\\% $$\n\n- Sindrome di Edwards:\n  $$ VPP = \\frac{(0.97 \\times 0.0002)}{(0.97 \\times 0.0002) + (1 - 0.999) \\times (1 - 0.0002)} \\approx 16.2\\% $$\n\n- Sindrome di Patau:\n  $$ VPP = \\frac{(0.91 \\times 0.0001)}{(0.91 \\times 0.0001) + (1 - 0.999) \\times (1 - 0.0001)} \\approx 8.3\\% $$\n\nQuesti calcoli rivelano VPP molto bassi, specialmente per condizioni molto rare come la sindrome di Patau. Anche in questo caso, dunque, il teorema di Bayes ci mostra che la probabilità che un risultato positivo sia effettivamente corretto dipende non solo dall'accuratezza del test, ma anche dalla prevalenza della condizione nella popolazione testata. Per questo motivo, il NIPT risulta più affidabile nelle categorie ad alto rischio.\n\nIn conclusione, mentre il NIPT è uno strumento prezioso per lo screening prenatale, è fondamentale interpretare i risultati con cautela, considerando il contesto specifico di ogni paziente e la prevalenza della condizione nella popolazione di riferimento.\n\n:::\n\n## La Fallacia del Procuratore\n\nIl teorema di Bayes non è rilevante solo in ambito medico; è altrettanto cruciale nel contesto legale, dove un errore logico noto come **fallacia del procuratore** può avere conseguenze significative. Questa fallacia si verifica quando si confonde la probabilità di un risultato dato un evento con la probabilità dell'evento dato il risultato. In ambito giudiziario, ciò accade spesso quando si scambia la probabilità di ottenere una corrispondenza del DNA se una persona è innocente con la probabilità che una persona sia innocente dato che il test del DNA ha prodotto una corrispondenza.\n\n::: {#exm-}\n\nSupponiamo che un test del DNA venga utilizzato per identificare un sospetto in una popolazione di 65 milioni di persone. Consideriamo i seguenti parametri:\n\n- **Sensibilità**: $P(T^+ \\mid C) = 99\\%$, ovvero la probabilità che il test identifichi correttamente il colpevole.\n- **Specificità**: $P(T^- \\mid I) = 99.99997\\%$, ovvero la probabilità che il test identifichi correttamente un innocente.\n- **Prevalenza**: $P(C) = \\frac{1}{65.000.000}$, ovvero la probabilità a priori che una persona qualsiasi sia il colpevole.\n\nUn campione di DNA è stato trovato sulla scena del crimine e confrontato con quello di una persona nel database. Determiniamo la probabilità che questa persona sia effettivamente il colpevole, dato che il test è positivo ($T^+$).\n\nPasso 1: Calcolo della Probabilità del Test Positivo $P(T^+)$.\n\nLa probabilità di ottenere un test positivo ($T^+$) è data dalla somma delle probabilità di un risultato positivo per un colpevole e per un innocente:\n\n$$\nP(T^+) = P(T^+ \\mid C) \\cdot P(C) + P(T^+ \\mid I) \\cdot P(I),\n$$\n\ndove $P(I) = 1 - P(C)$ è la probabilità che una persona sia innocente e $P(T^+ \\mid I) = 1 - \\text{Specificità}$.\n\nSostituiamo i valori noti:\n\n$$\nP(T^+) = 0.99 \\cdot \\frac{1}{65.000.000} + (1 - 0.9999997) \\cdot \\frac{64.999.999}{65.000.000}.\n$$\n\nEseguiamo i calcoli:\n\n$$\nP(T^+) \\approx 0.99 \\cdot 1.5385 \\times 10^{-8} + 0.0000003 \\cdot 0.9999999,\n$$\n\n$$\nP(T^+) \\approx 1.5231 \\times 10^{-8} + 2.9999997 \\times 10^{-7},\n$$\n\n$$\nP(T^+) \\approx 3.1523 \\times 10^{-7}.\n$$\n\n\nPasso 2: Probabilità Condizionale che il Sospetto sia Colpevole Dato un Test Positivo. \n\nUtilizzando il teorema di Bayes, la probabilità a posteriori che il sospetto sia colpevole, dato un test positivo, è:\n\n$$\nP(C \\mid T^+) = \\frac{P(T^+ \\mid C) \\cdot P(C)}{P(T^+)}.\n$$\n\nSostituiamo i valori calcolati:\n\n$$\nP(C \\mid T^+) = \\frac{0.99 \\cdot \\frac{1}{65.000.000}}{3.1523 \\times 10^{-7}},\n$$\n\n$$\nP(C \\mid T^+) = \\frac{0.99 \\cdot 1.5385 \\times 10^{-8}}{3.1523 \\times 10^{-7}},\n$$\n\n$$\nP(C \\mid T^+) \\approx 0.0483.\n$$\n\nLa probabilità che il sospetto sia effettivamente il colpevole, dato che il test del DNA è positivo, è quindi circa **4.83%**, nonostante la specificità estremamente elevata del test.\n\nQuesto risultato dimostra quanto sia importante considerare la bassa prevalenza del colpevole nella popolazione. Affermare, ad esempio, che \"c'è solo una probabilità su 3 milioni che il sospetto sia innocente\" confonde la specificità del test ($P(T^- \\mid I)$) con la probabilità condizionale di colpevolezza ($P(C \\mid T^+)$).\n\nIn realtà, la probabilità che il sospetto sia colpevole dato un test positivo è molto più bassa, a causa della prevalenza estremamente ridotta. Questo errore logico può portare a gravi ingiustizie, poiché non si considera che i falsi positivi diventano statisticamente più rilevanti quando il numero di innocenti testati è molto alto.\n\nPer chiarire, confondere $P(T^+ \\mid I)$ con $P(I \\mid T^+)$ è analogo a confondere \"Quanto è probabile che il DNA di una persona corrisponda al campione, se è innocente?\" con \"Quanto è probabile che una persona sia innocente, dato che il suo DNA corrisponde al campione?\".\n\nIn conclusione, la fallacia del procuratore mette in evidenza l'importanza di interpretare correttamente i risultati dei test probabilistici in contesti legali. L'uso del teorema di Bayes è essenziale per evitare errori logici e per garantire che le decisioni siano basate su una comprensione accurata delle probabilità condizionali.\n:::\n\n## Probabilità Inversa\n\nGli esempi precedenti evidenziano la differenza tra due domande fondamentali. La prima è: \"Qual è la probabilità di osservare un determinato risultato, supponendo che una certa ipotesi sia vera?\" La seconda, invece, è: \"Qual è la probabilità che un'ipotesi sia vera, dato il risultato osservato?\"\n\nUn esempio che risponde alla prima domanda potrebbe essere questo: supponiamo che la probabilità di ottenere testa nel lancio di una moneta sia 0.5 (ipotesi). Qual è la probabilità di ottenere 0 teste in cinque lanci?\n\nPer la seconda domanda, un esempio potrebbe essere: supponiamo di aver ottenuto 0 teste in 5 lanci di una moneta (evidenza). Qual è la probabilità che la moneta sia effettivamente bilanciata, alla luce di questa osservazione?\n\nPer molto tempo, lo studio della probabilità si è concentrato principalmente sulla prima domanda. Tuttavia, nel XVIII secolo, il reverendo Thomas Bayes iniziò a riflettere sulla seconda domanda, dando origine a quello che oggi chiamiamo **probabilità inversa**.\n\nQuesto approccio ha generato numerose controversie nella storia della statistica, in gran parte perché influenza molti ambiti. Ad esempio, possiamo chiederci: quanto è probabile che un'ipotesi scientifica sia vera, dato il risultato di un esperimento? Per stimare questa probabilità — un compito che molti scienziati ritengono essenziale per la statistica moderna — è necessario fare uso del teorema di Bayes e delle probabilità a priori.\n\n## Riflessioni Conclusive\n\nIn questo capitolo abbiamo esplorato vari esempi, principalmente nel campo medico e forense, per illustrare come il teorema di Bayes permetta di combinare le informazioni derivate dalle osservazioni con le conoscenze precedenti (priori), aggiornando così il nostro grado di convinzione rispetto a un'ipotesi. Il teorema di Bayes fornisce un meccanismo razionale, noto come \"aggiornamento bayesiano\", che ci consente di ricalibrare le nostre convinzioni iniziali alla luce di nuove evidenze.\n\nUna lezione fondamentale che il teorema di Bayes ci insegna, sia nella ricerca scientifica che nella vita quotidiana, è che spesso non ci interessa tanto conoscere la probabilità che qualcosa accada assumendo vera un'ipotesi, quanto piuttosto la probabilità che un'ipotesi sia vera, dato che abbiamo osservato una certa evidenza. In altre parole, la forza del teorema di Bayes sta nella sua capacità di affrontare direttamente il **problema inverso**, cioè come dedurre la verità di un'ipotesi a partire dalle osservazioni.\n\nIl framework bayesiano per l'inferenza probabilistica offre un approccio generale per comprendere come i problemi di induzione possano essere risolti in linea di principio e, forse, anche come possano essere affrontati dalla mente umana.\n\nIn questo capitolo ci siamo concentrati sull'applicazione del teorema di Bayes utilizzando probabilità puntuali. Tuttavia, il teorema esprime pienamente il suo potenziale quando sia l'evidenza che i gradi di certezza a priori delle ipotesi sono rappresentati attraverso distribuzioni di probabilità continue. Questo sarà l'argomento centrale nella prossima sezione della dispensa, dove approfondiremo il flusso di lavoro bayesiano e l'uso di distribuzioni continue nell'aggiornamento bayesiano.\n\n## Informazioni sull'Ambiente di Sviluppo {.unnumbered}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n#> R version 4.4.2 (2024-10-31)\n#> Platform: aarch64-apple-darwin20\n#> Running under: macOS Sequoia 15.2\n#> \n#> Matrix products: default\n#> BLAS:   /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRblas.0.dylib \n#> LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0\n#> \n#> locale:\n#> [1] C/UTF-8/C/C/C/C\n#> \n#> time zone: Europe/Rome\n#> tzcode source: internal\n#> \n#> attached base packages:\n#> [1] stats     graphics  grDevices utils     datasets  methods   base     \n#> \n#> other attached packages:\n#>  [1] viridis_0.6.5     viridisLite_0.4.2 gridExtra_2.3     patchwork_1.3.0  \n#>  [5] bayesplot_1.11.1  psych_2.4.6.26    scales_1.3.0      markdown_1.13    \n#>  [9] knitr_1.49        lubridate_1.9.4   forcats_1.0.0     stringr_1.5.1    \n#> [13] dplyr_1.1.4       purrr_1.0.2       readr_2.1.5       tidyr_1.3.1      \n#> [17] tibble_3.2.1      ggplot2_3.5.1     tidyverse_2.0.0   rio_1.2.3        \n#> [21] here_1.0.1       \n#> \n#> loaded via a namespace (and not attached):\n#>  [1] utf8_1.2.4        generics_0.1.3    stringi_1.8.4     lattice_0.22-6   \n#>  [5] hms_1.1.3         digest_0.6.37     magrittr_2.0.3    evaluate_1.0.1   \n#>  [9] grid_4.4.2        timechange_0.3.0  fastmap_1.2.0     rprojroot_2.0.4  \n#> [13] jsonlite_1.8.9    fansi_1.0.6       mnormt_2.1.1      cli_3.6.3        \n#> [17] rlang_1.1.4       munsell_0.5.1     withr_3.0.2       tools_4.4.2      \n#> [21] parallel_4.4.2    tzdb_0.4.0        colorspace_2.1-1  pacman_0.5.1     \n#> [25] vctrs_0.6.5       R6_2.5.1          lifecycle_1.0.4   htmlwidgets_1.6.4\n#> [29] pkgconfig_2.0.3   pillar_1.9.0      gtable_0.3.6      glue_1.8.0       \n#> [33] xfun_0.49         tidyselect_1.2.1  farver_2.1.2      htmltools_0.5.8.1\n#> [37] nlme_3.1-166      rmarkdown_2.29    compiler_4.4.2\n```\n:::\n\n\n\n\n## Bibliografia {.unnumbered}\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}